apiVersion: apps/v1
kind: Deployment
metadata:
  name: http
spec:
  selector:
    matchLabels:
      app: http
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: http
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: python:3
          command: ["python"]
          args: ["/code/http_server.py"]
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /code
              name: code
      volumes:
        - name: code
          configMap:
            name: code
